export enum EButtonStyleType {
  PRIMARY = 'PRIMARY',
  WHITE = 'WHITE',
  WHITE_GRAY = 'WHITE_GRAY',
  DANGER = 'DANGER',

  OUTLINE_GEYSER = 'OUTLINE_GEYSER',
  OUTLINE_GERALDINE = 'OUTLINE_GERALDINE',

  TRANSPARENT_GEYSER = 'TRANSPARENT_GEYSER',
  TRANSPARENT_SUCCESS = 'TRANSPARENT_SUCCESS',
  TRANSPARENT_DANGER = 'TRANSPARENT_DANGER',
}
